---
title: "Discussion 1 Introduction to Data"
author: "Stats 67 Teaching Team"
format: html
---

# Load Packages

```{r}
library(datasets)
library(tidyverse)
```


# About R

Basic functions and language

```{r}
print('hello woRld')
birth_years <- c(1996, 2001, 1999)
print(birth_years)
```

# Dataframe in R

```{r}
data.frame(person = c('Jack', 'Allen', 'Lisa'), birth_years = birth_years)

?data.frame
```

You could also check the use of a function or a package by searching in the help panel.

# Tidyverse

After function names do not leave any spaces.

Before and after operators (e.g. <-, =) leave spaces.

Put a space after a comma, not before.

Object names are all lower case, with words separated by an underscore.


# Markdown and Quarto

word

_word_

__word__

~~word~~

If you need R variables in text, you can do this: the birth_years are:
`r birth_years`

# Load mtcars Dataset

```{r}
mtcars <- mtcars %>% 
  mutate(am = as.factor(am))
```

# Dataset

## Description given by the author

```{r}
?mtcars
```

# First Look

Take a glimpse at the data.

1.  How many rows and columns are there in the "mtcars" dataset?
2.  Any categorical variables?
3.  Any numeric variables?

```{r}
glimpse(mtcars)
```

# First and last few lines

```{r}
head(mtcars)
```

```{r}
tail(mtcars)
```


